name: Android build prod by release AAB

permissions:
  contents: write

on:
  push:
    tags:
      - "v*-aab"
      - "!v*-qa*"
      - "!v*-hotfix"

jobs:
  versions:
    uses: ./.github/workflows/versions.yml
    with:
      branch: prod

  android-build:
    uses: ./.github/workflows/build-android-and-upload.yml
    secrets: inherit
    needs: [versions]
    with:
      environment: prod
      branch: prod
      artifactName: app-prod-release.aab
      buildAAB: true
      appVersion: ${{ needs.versions.outputs.PROD_VERSION }}

  upload-artifacts:
    name: upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-prod-release.aab
          path: .
      - name: install OSSUTIL
        run: |
          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
      - name: Configure OSS
        env:
          OSS_KEY: ${{ secrets.OSS_KEY }}
          OSS_ID: ${{ secrets.OSS_ID }}
        run: |
          touch ~/.ossutilconfig
          chmod 644 ~/.ossutilconfig
          cat >>~/.ossutilconfig <<END
          [Credentials]
          language=EN
          endpoint=oss-cn-hongkong.aliyuncs.com
          accessKeyID=$OSS_ID
          accessKeySecret=$OSS_KEY
          END
      - name: Upload to OSS
        run: yes | ossutil64 cp ./app-prod-release.aab oss://blockvenus-hk/abbs/BIMWallet.aab
