name: build QA

permissions:
  contents: write

on:
  push:
    branches:
      - qa

jobs:
  versions:
    uses: ./.github/workflows/versions.yml
    with:
      branch: qa

  create-qa-tag:
    needs: [versions]
    uses: ./.github/workflows/createTag.yml
    with:
      tag: ${{ needs.versions.outputs.QA_TAG }}

  android-build:
    needs: [versions, create-qa-tag]
    uses: ./.github/workflows/build-android-and-upload.yml
    secrets: inherit
    with:
      environment: qa
      branch: qa
      artifactName: app-qa-release.apk
      buildAAB: false
      appVersion: ${{ needs.versions.outputs.QA_VERSION }}

  upload-to-release:
    name: upload-to-release
    needs: [versions, android-build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-qa-release.apk
          path: .
      - name: push to github
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.versions.outputs.QA_TAG}}
          name: ${{ needs.versions.outputs.QA_TAG }}
          prerelease: true
          files: |
            ./app-qa-release.apk

  ios-build:
    name: IOS Build
    needs: [versions, create-qa-tag]
    uses: ./.github/workflows/build-ios-and-upload.yml
    secrets: inherit
    with:
      environment: qa
      branch: qa
      appVersion: ${{ needs.versions.outputs.QA_VERSION }}
