on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  createTag:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v7
        env:
          TAG: ${{ inputs.tag }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.TAG}`,
              sha: context.sha
            })
