name: Android build prod by hotfix

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*-hotfix'
      - '!v*-qa*'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: yarn

      - name: Set up JDK envronment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: set ENV
        env:
          PASSWORD_CRYPTO_KEY: ${{ secrets.PASSWORD_CRYPTO_KEY }}
          UPLOAD_KEYSTORE: ${{secrets.UPLOAD_KEYSTORE}}
          SIGN_ALIAS: ${{secrets.SIGN_ALIAS}}
          SIGN_KEY: ${{secrets.SIGN_KEY}}
          PRODUCTION_ANDROID: ${{ secrets.PRODUCTION_ANDROID }}
        run: |
          echo $UPLOAD_KEYSTORE | base64 --decode > ./android/app/release.keystore.jks
          echo "" > .env
          cat >>.env <<END
          APP_ENV=prod
          PASSWORD_CRYPTO_KEY=$PASSWORD_CRYPTO_KEY
          END
      - name: code push
        env:
          APP_API_TOKEN: ${{ secrets.APP_API_TOKEN }}
          CODE_PUSH_PRIVATE_KEY: ${{ secrets.CODE_PUSH_PRIVATE_KEY }}
        run: |
          echo $CODE_PUSH_PRIVATE_KEY | base64 --decode > ./codepush.pem
          npm install -g appcenter-cli
          appcenter login --token $APP_API_TOKEN
          appcenter codepush release-react -a yuqi.wang-confluxnetwork.org/SwiftShield-1 -d Production --entry-file ./index.ts --private-key-path ./codepush.pem
