name: Android build

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node_version: 'lts/-n'
      - name: install dependencies
        run: yarn

      - name: Set up JDK envronment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
      - name: Build Android qa Release
        run: |
          echo APP_ENV=qa >> .env
          cd android && ./gradlew app:assembleQaRelease && cd ..
      - name: Build Android Release
        run: |
          echo APP_ENV=prod >> .env
          cd android && ./gradlew app:assembleProdRelease && cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            files: |
             ./android/app/build/outputs/apk/prod/release/app-prod-release.apk
             ./android/app/build/outputs/apk/qa/release/app-qa-release.apk
