name: build QA

permissions:
  contents: write

on:
  push:
    tags:
      - "v*-qa"
jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: qa

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: yarn

      - name: Set up JDK envronment
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
      - name: Set env and Build Android Release
        env:
          PASSWORD_CRYPTO_KEY: ${{ secrets.PASSWORD_CRYPTO_KEY }}
          STAGING_ANDROID: ${{ secrets.STAGING_ANDROID }}
        run: |
          echo "" > .env
          cat >>.env <<END
          APP_ENV=qa
          PASSWORD_CRYPTO_KEY=$PASSWORD_CRYPTO_KEY
          END
          cd android && ./gradlew app:assembleQaRelease && cd ..
      - name: rename apk
        run: mv ./android/app/build/outputs/apk/qa/release/app-qa-release.apk ./android/app/build/outputs/apk/qa/release/BIMWallet-$GITHUB_REF_NAME.apk
      - name: push to github
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./android/app/build/outputs/apk/qa/release/BIMWallet-$GITHUB_REF_NAME.apk
  ios-build:
    name: IOS Build
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: qa

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: yarn


      - name: patch and install pod
        env:
          PASSWORD_CRYPTO_KEY: ${{ secrets.PASSWORD_CRYPTO_KEY }}
          STAGING_ANDROID: ${{ secrets.STAGING_ANDROID }}
        run: |
          echo "" > .env
          cat >>.env <<END
          APP_ENV=qa
          PASSWORD_CRYPTO_KEY=$PASSWORD_CRYPTO_KEY
          END
          yarn patchPackage && cd ios && pod install --repo-update && cd ..

      - name: Build IOS App
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: ios/BIMWallet.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: ios/BIMWallet.xcworkspace
          code-signing-identity: 'iPhone Distribution'

      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: "output.ipa"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
