name: Version Check

on:
  push:
    branches:
      - dev

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # https://yarnpkg.com/features/release-workflow/#commit-history
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: ${{ matrix.node-version }}
      - name: version check
        run: |
          yarn install
          yarn version check
