on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      PACKAGE_VERSION:
        description: "The package version"
        value: ${{ jobs.version.outputs.PACKAGE_VERSION}}
      PROD_VERSION:
        description: "The production version"
        value: ${{ jobs.version.outputs.PROD_VERSION}}
      PROD_TAG:
        description: "The production tag"
        value: ${{ jobs.version.outputs.PROD_TAG}}
      QA_VERSION:
        description: "The version"
        value: ${{ jobs.version.outputs.QA_VERSION}}
      QA_TAG:
        description: "The tag"
        value: ${{ jobs.version.outputs.QA_TAG}}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_VERSION: ${{ steps.get-package-version.outputs.PACKAGE_VERSION }}
      PROD_VERSION: ${{ fromJson(steps.generate-version.outputs.result).prod_version }}
      PROD_TAG: ${{ fromJson(steps.generate-version.outputs.result).prod_tag }}
      QA_VERSION: ${{ fromJson(steps.generate-version.outputs.result).version }}
      QA_TAG: ${{ fromJson(steps.generate-version.outputs.result).tag }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{inputs.branch}}

      - name: get package.json version
        id: get-package-version
        run: |
          echo "PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"

      - name: generate release version
        id: generate-version
        uses: actions/github-script@v7
        env:
          PACKAGE_VERSION: ${{ steps.get-package-version.outputs.PACKAGE_VERSION }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return await require('.github/scripts/generateReleaseVersion.js')({github, context, core})
