name: Version Update

on:
  push:
    branches:
      - dev
      - '!qa-release/dev'

jobs:
  createPullRequest:
    name: Create QA pull request
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update Version and Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/versionAndPR.js')
            await script({github, context, core, exec})
